api_platform:
    title: BilemoAPI's documentation
    description: 'API description'
    version: '1.0.0'
    show_webby: false
    enable_docs: true
    enable_re_doc: true
    http_cache:
        etag: true
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
             apiKey:
                name: Authorization
                type: header
    collection:
        pagination:
            enabled: true
            client_enabled: true
            items_per_page: 4